/* eslint-disable */
export const departementsRegions = [
    {
        "nom":"France",
        "code": "france",
        "level": "france"
    },
    {
      "nom":"Guadeloupe",
      "code":"region:01",
      "level":"region"
    },
    {
      "nom":"Martinique",
      "code":"region:02",
      "level":"region"
    },
    {
      "nom":"Guyane",
      "code":"region:03",
      "level":"region"
    },
    {
      "nom":"La R\u00e9union",
      "code":"region:04",
      "level":"region"
    },
    {
      "nom":"Mayotte",
      "code":"region:06",
      "level":"region"
    },
    {
      "nom":"\u00cele-de-France",
      "code":"region:11",
      "level":"region"
    },
    {
      "nom":"Paris",
      "code":"departement:75",
      "level":"departement"
    },
    {
      "nom":"Seine-et-Marne",
      "code":"departement:77",
      "level":"departement"
    },
    {
      "nom":"Yvelines",
      "code":"departement:78",
      "level":"departement"
    },
    {
      "nom":"Essonne",
      "code":"departement:91",
      "level":"departement"
    },
    {
      "nom":"Hauts-de-Seine",
      "code":"departement:92",
      "level":"departement"
    },
    {
      "nom":"Seine-Saint-Denis",
      "code":"departement:93",
      "level":"departement"
    },
    {
      "nom":"Val-de-Marne",
      "code":"departement:94",
      "level":"departement"
    },
    {
      "nom":"Val-d'Oise",
      "code":"departement:95",
      "level":"departement"
    },
    {
      "nom":"Centre-Val de Loire",
      "code":"region:24",
      "level":"region"
    },
    {
      "nom":"Cher",
      "code":"departement:18",
      "level":"departement"
    },
    {
      "nom":"Eure-et-Loir",
      "code":"departement:28",
      "level":"departement"
    },
    {
      "nom":"Indre",
      "code":"departement:36",
      "level":"departement"
    },
    {
      "nom":"Indre-et-Loire",
      "code":"departement:37",
      "level":"departement"
    },
    {
      "nom":"Loir-et-Cher",
      "code":"departement:41",
      "level":"departement"
    },
    {
      "nom":"Loiret",
      "code":"departement:45",
      "level":"departement"
    },
    {
      "nom":"Bourgogne-Franche-Comt\u00e9",
      "code":"region:27",
      "level":"region"
    },
    {
      "nom":"C\u00f4te-d'Or",
      "code":"departement:21",
      "level":"departement"
    },
    {
      "nom":"Doubs",
      "code":"departement:25",
      "level":"departement"
    },
    {
      "nom":"Jura",
      "code":"departement:39",
      "level":"departement"
    },
    {
      "nom":"Ni\u00e8vre",
      "code":"departement:58",
      "level":"departement"
    },
    {
      "nom":"Haute-Sa\u00f4ne",
      "code":"departement:70",
      "level":"departement"
    },
    {
      "nom":"Sa\u00f4ne-et-Loire",
      "code":"departement:71",
      "level":"departement"
    },
    {
      "nom":"Yonne",
      "code":"departement:89",
      "level":"departement"
    },
    {
      "nom":"Territoire de Belfort",
      "code":"departement:90",
      "level":"departement"
    },
    {
      "nom":"Normandie",
      "code":"region:28",
      "level":"region"
    },
    {
      "nom":"Calvados",
      "code":"departement:14",
      "level":"departement"
    },
    {
      "nom":"Eure",
      "code":"departement:27",
      "level":"departement"
    },
    {
      "nom":"Manche",
      "code":"departement:50",
      "level":"departement"
    },
    {
      "nom":"Orne",
      "code":"departement:61",
      "level":"departement"
    },
    {
      "nom":"Seine-Maritime",
      "code":"departement:76",
      "level":"departement"
    },
    {
      "nom":"Hauts-de-France",
      "code":"region:32",
      "level":"region"
    },
    {
      "nom":"Aisne",
      "code":"departement:02",
      "level":"departement"
    },
    {
      "nom":"Nord",
      "code":"departement:59",
      "level":"departement"
    },
    {
      "nom":"Oise",
      "code":"departement:60",
      "level":"departement"
    },
    {
      "nom":"Pas-de-Calais",
      "code":"departement:62",
      "level":"departement"
    },
    {
      "nom":"Somme",
      "code":"departement:80",
      "level":"departement"
    },
    {
      "nom":"Grand Est",
      "code":"region:44",
      "level":"region"
    },
    {
      "nom":"Ardennes",
      "code":"departement:08",
      "level":"departement"
    },
    {
      "nom":"Aube",
      "code":"departement:10",
      "level":"departement"
    },
    {
      "nom":"Marne",
      "code":"departement:51",
      "level":"departement"
    },
    {
      "nom":"Haute-Marne",
      "code":"departement:52",
      "level":"departement"
    },
    {
      "nom":"Meurthe-et-Moselle",
      "code":"departement:54",
      "level":"departement"
    },
    {
      "nom":"Meuse",
      "code":"departement:55",
      "level":"departement"
    },
    {
      "nom":"Moselle",
      "code":"departement:57",
      "level":"departement"
    },
    {
      "nom":"Bas-Rhin",
      "code":"departement:67",
      "level":"departement"
    },
    {
      "nom":"Haut-Rhin",
      "code":"departement:68",
      "level":"departement"
    },
    {
      "nom":"Vosges",
      "code":"departement:88",
      "level":"departement"
    },
    {
      "nom":"Pays de la Loire",
      "code":"region:52",
      "level":"region"
    },
    {
      "nom":"Loire-Atlantique",
      "code":"departement:44",
      "level":"departement"
    },
    {
      "nom":"Maine-et-Loire",
      "code":"departement:49",
      "level":"departement"
    },
    {
      "nom":"Mayenne",
      "code":"departement:53",
      "level":"departement"
    },
    {
      "nom":"Sarthe",
      "code":"departement:72",
      "level":"departement"
    },
    {
      "nom":"Vend\u00e9e",
      "code":"departement:85",
      "level":"departement"
    },
    {
      "nom":"Bretagne",
      "code":"region:53",
      "level":"region"
    },
    {
      "nom":"C\u00f4tes-d'Armor",
      "code":"departement:22",
      "level":"departement"
    },
    {
      "nom":"Finist\u00e8re",
      "code":"departement:29",
      "level":"departement"
    },
    {
      "nom":"Ille-et-Vilaine",
      "code":"departement:35",
      "level":"departement"
    },
    {
      "nom":"Morbihan",
      "code":"departement:56",
      "level":"departement"
    },
    {
      "nom":"Nouvelle-Aquitaine",
      "code":"region:75",
      "level":"region"
    },
    {
      "nom":"Charente",
      "code":"departement:16",
      "level":"departement"
    },
    {
      "nom":"Charente-Maritime",
      "code":"departement:17",
      "level":"departement"
    },
    {
      "nom":"Corr\u00e8ze",
      "code":"departement:19",
      "level":"departement"
    },
    {
      "nom":"Creuse",
      "code":"departement:23",
      "level":"departement"
    },
    {
      "nom":"Dordogne",
      "code":"departement:24",
      "level":"departement"
    },
    {
      "nom":"Gironde",
      "code":"departement:33",
      "level":"departement"
    },
    {
      "nom":"Landes",
      "code":"departement:40",
      "level":"departement"
    },
    {
      "nom":"Lot-et-Garonne",
      "code":"departement:47",
      "level":"departement"
    },
    {
      "nom":"Pyr\u00e9n\u00e9es-Atlantiques",
      "code":"departement:64",
      "level":"departement"
    },
    {
      "nom":"Deux-S\u00e8vres",
      "code":"departement:79",
      "level":"departement"
    },
    {
      "nom":"Vienne",
      "code":"departement:86",
      "level":"departement"
    },
    {
      "nom":"Haute-Vienne",
      "code":"departement:87",
      "level":"departement"
    },
    {
      "nom":"Occitanie",
      "code":"region:76",
      "level":"region"
    },
    {
      "nom":"Ari\u00e8ge",
      "code":"departement:09",
      "level":"departement"
    },
    {
      "nom":"Aude",
      "code":"departement:11",
      "level":"departement"
    },
    {
      "nom":"Aveyron",
      "code":"departement:12",
      "level":"departement"
    },
    {
      "nom":"Gard",
      "code":"departement:30",
      "level":"departement"
    },
    {
      "nom":"Haute-Garonne",
      "code":"departement:31",
      "level":"departement"
    },
    {
      "nom":"Gers",
      "code":"departement:32",
      "level":"departement"
    },
    {
      "nom":"H\u00e9rault",
      "code":"departement:34",
      "level":"departement"
    },
    {
      "nom":"Lot",
      "code":"departement:46",
      "level":"departement"
    },
    {
      "nom":"Loz\u00e8re",
      "code":"departement:48",
      "level":"departement"
    },
    {
      "nom":"Hautes-Pyr\u00e9n\u00e9es",
      "code":"departement:65",
      "level":"departement"
    },
    {
      "nom":"Pyr\u00e9n\u00e9es-Orientales",
      "code":"departement:66",
      "level":"departement"
    },
    {
      "nom":"Tarn",
      "code":"departement:81",
      "level":"departement"
    },
    {
      "nom":"Tarn-et-Garonne",
      "code":"departement:82",
      "level":"departement"
    },
    {
      "nom":"Auvergne-Rh\u00f4ne-Alpes",
      "code":"region:84",
      "level":"region"
    },
    {
      "nom":"Ain",
      "code":"departement:01",
      "level":"departement"
    },
    {
      "nom":"Allier",
      "code":"departement:03",
      "level":"departement"
    },
    {
      "nom":"Ard\u00e8che",
      "code":"departement:07",
      "level":"departement"
    },
    {
      "nom":"Cantal",
      "code":"departement:15",
      "level":"departement"
    },
    {
      "nom":"Dr\u00f4me",
      "code":"departement:26",
      "level":"departement"
    },
    {
      "nom":"Is\u00e8re",
      "code":"departement:38",
      "level":"departement"
    },
    {
      "nom":"Loire",
      "code":"departement:42",
      "level":"departement"
    },
    {
      "nom":"Haute-Loire",
      "code":"departement:43",
      "level":"departement"
    },
    {
      "nom":"Puy-de-D\u00f4me",
      "code":"departement:63",
      "level":"departement"
    },
    {
      "nom":"Rh\u00f4ne",
      "code":"departement:69",
      "level":"departement"
    },
    {
      "nom":"Savoie",
      "code":"departement:73",
      "level":"departement"
    },
    {
      "nom":"Haute-Savoie",
      "code":"departement:74",
      "level":"departement"
    },
    {
      "nom":"Provence-Alpes-C\u00f4te d'Azur",
      "code":"region:93",
      "level":"region"
    },
    {
      "nom":"Alpes-de-Haute-Provence",
      "code":"departement:04",
      "level":"departement"
    },
    {
      "nom":"Hautes-Alpes",
      "code":"departement:05",
      "level":"departement"
    },
    {
      "nom":"Alpes-Maritimes",
      "code":"departement:06",
      "level":"departement"
    },
    {
      "nom":"Bouches-du-Rh\u00f4ne",
      "code":"departement:13",
      "level":"departement"
    },
    {
      "nom":"Var",
      "code":"departement:83",
      "level":"departement"
    },
    {
      "nom":"Vaucluse",
      "code":"departement:84",
      "level":"departement"
    },
    {
      "nom":"Corse",
      "code":"region:94",
      "level":"region"
    },
    {
      "nom":"Corse-du-Sud",
      "code":"departement:2A",
      "level":"departement"
    },
    {
      "nom":"Haute-Corse",
      "code":"departement:2B",
      "level":"departement"
    }
  ]
